### ISSUE TITLE
Swift SDK MVP

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-sdk-rust#1]
Features:

- [x] Signing on demand
- [x] Transaction ID regeneration
- [x] Request backoff only after attempting all nodes
- [x] Use random nodes
- [x] Deterministic serialization of transfers
- [x] Paid queries
- [x] Accounts
- [x] Getting Started in the readme 
- [x] Mirror the repos to the SDK core
- [x] Transfer transaction and account balance query example
- [ ] Topic message query (to test mirror node connection)

**Comment by mehcode** [comment]
>  Mirror the repos to the SDK core

What does this mean

**Comment by SimiHunjan** [comment]
@danielakhterov can expand. He had mentioned you guys were trying to mirror something to the SDK core repo that you were working on.

**Comment by janaakhterov** [comment]
I think that was what we did with "mirroring" the Swift SDK within core into a separate repo hedera-swift-sdk.
