### ISSUE TITLE
[swift/API] `TransactionRecord`

### ISSUE THREAD

**Issue by ghost** [hiero-ledger/hiero-sdk-rust#265]
tracking issue for missing fields / methods in `TransactionRecord`

- [x] `transactionId` should be a `TransactionId`
- [x] `contractFunctionResult`
- [x] `transfers`
- [x] `tokenTransfers`
- [x] ~`tokenTransferList`~
- [x] `tokenNftTransfers`
- [x] `assessedCustomFees`

**Comment by izik1** [comment]
Note: Once both #304 and #308 are merged, this will be done
