### ISSUE TITLE
Confirm the SDK behavior when trying to mint a large number of NFTs

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-sdk-rust#485]

**Comment by JeromeK13** [comment]
Hey @SimiHunjan 

We're currently testing the SDK on our side. What is a "large" number, we could cover that if still needed

KR
Jerome

**Comment by izik1** [comment]
Hi! Sorry for not seeing this, to be clear, we have a test for this

This issue is mostly still open because I'm not sure what we want out of it before closing it.

So, I think I'll close it, and @SimiHunjan can re-open it if she wants.
