### ISSUE TITLE
`ContractFunctionParamters::add_string(...)` index out of bounds

### ISSUE THREAD

**Issue by emilHof** [hiero-ledger/hiero-sdk-rust#715]
### Description

Adding a `String` of `length > 32` to `ContractFunctionParameters`  results in a index out of bounds panic. It seems to be originating from `right_pad_32_bytes(...)` function in `contract_function_paramters.rs` on line 956. Of course, this could be intentional and `add_string` may be limited to `length <= 32` on purpose. Yet, if this is the case, then i am not able to find this being mentioned anywhere in the docs (maybe because i am not looking hard enough though hahah).

### Steps to reproduce

```rust
let s = /* some string longer than 32 characters */;
ContractFunctionParameters::new().add_string(s); // panics!
```

### Additional context

```
thread 'test::test_add' panicked at /home/emil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hedera-0.20.2/src/cont
ract/contract_function_parameters.rs:962:11:
range end index 88 out of range for slice of length 32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Hedera network

testnet

### Version

v0.20.2

### Operating system

None

**Comment by izik1** [comment]
Hi! Definitely a bug

**Comment by emilHof** [comment]
Hi @izik1 ! oh, wow, you're quick! well done ! :D

**Comment by izik1** [comment]
Yeah, it's kinda rare that off schedule releases happen though, so, you'll probably be sitting around for a bit (until Monday) unless you're willing to use a git release temporarily

**Comment by izik1** [comment]
err, git release -> git revision, to be clear

**Comment by emilHof** [comment]
ohh, no worries about that at all! thank you for jumping on this issue so fast and getting it fixed! using a versioned git dependency for now is not a problem at all ! thank youu @izik1 ! :))
